<a href="https://colab.research.google.com/github/Indongspace/streamlit-mulcamp/blob/main/api_crawling_240201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
SERVICE_KEY = '5379664f57696e6435314372485a54'

In [ ]:
URL = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/1/20/'
URL

'http://openapi.seoul.go.kr:8088/5379664f57696e6435314372485a54/json/tbLnOpendataRtmsV/1/20/'

In [ ]:
import requests
import json
import pandas as pd
import xmltodict

req = requests.get(URL)
req

In [ ]:
content = req.json()
#content
result = pd.DataFrame(content['tbLnOpendataRtmsV']['row'])
result.to_csv('seoul result.csv')

In [ ]:
URL = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/xml/tbLnOpendataRtmsV/1/5/'
URL

'http://openapi.seoul.go.kr:8088/5379664f57696e6435314372485a54/xml/tbLnOpendataRtmsV/1/5/'

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

req = requests.get(URL)
#req.content
soup = BeautifulSoup(req.content,'lxml')
years            = soup.find_all('acc_year')         # 접수년월
sgg_cds          = soup.find_all('sgg_cd')           # 자치구코드
sgg_nms          = soup.find_all('sgg_nm')           # 자치구명
bjdong_cds       = soup.find_all('bjdong_cd')        # 법정동코드
bjdong_nms       = soup.find_all('bjdong_nm')        # 법정동명
land_gbns        = soup.find_all('land_gbn')         # 지번구분
land_gbn_nms     = soup.find_all('land_gbn_nm')      # 지번구분명
land_gbn_nms     = soup.find_all('land_gbn_nm')      # 지번구분명
bonbeons         = soup.find_all('bonbeon')          # 본번
bubeons          = soup.find_all('bubeon')           # 부번
bldg_nms         = soup.find_all('bldg_nm')          # 건물명
deal_ymds        = soup.find_all('deal_ymd')         # 계약일
obj_amts         = soup.find_all('obj_amt')          # 물건금액(만원)
bldg_areas       = soup.find_all('bldg_area')        # 건물면적(㎡)
tot_areas        = soup.find_all('tot_area')         # 토지면적(㎡)
floors           = soup.find_all('floor')            # 층
right_gbns       = soup.find_all('right_gbn')        # 권리구분
cntl_ymds        = soup.find_all('cntl_ymd')         # 취소일
build_years      = soup.find_all('build_years')      # 건축년도
house_types      = soup.find_all('house_type')       # 건물용도
req_gbn          = soup.find_all('req_gbn')          # 신고구분
rdealer_lawdnms  = soup.find_all('rdealer_lawdnm')   # 신고한 개업공인중개사 시군구명
year_list           = []
sgg_cd_list         = []
bldg_nm_list        = []
obj_amt_list        = []
house_type_list     = []
rdealer_lawdnm_list = []
for year, sgg_cd, bldg_nm, obj_amt, house_type, rdealer_lawdnm in zip(years, sgg_cds, bldg_nms, obj_amts, house_types, rdealer_lawdnms):
  year_list.append(year.get_text())
  sgg_cd_list.append(sgg_cd.get_text())
  bldg_nm_list.append(bldg_nm.get_text())
  obj_amt_list.append(obj_amt.get_text())
  house_type_list.append(house_type.get_text())
  rdealer_lawdnm_list.append(rdealer_lawdnm.get_text())
df = pd.DataFrame({
    "acc_year": year_list,
    "sgg_cd": sgg_cd_list,
    "bldg_nm" : bldg_nm_list,
    "obj_amt": obj_amt_list,
    "house_type" : house_type_list,
    "rdealer_lawdnm": rdealer_lawdnm_list
})
df

C:\Users\SongInseung\AppData\Local\Temp\ipykernel_5228\4161532187.py:7: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  soup = BeautifulSoup(req.content,'lxml')

  acc_year sgg_cd    bldg_nm obj_amt house_type rdealer_lawdnm
0     2024  11560   여의도리슈빌DS   20600       오피스텔        서울 영등포구
1     2024  11740       도우빌라   36700      연립다세대         서울 강동구
2     2024  11320   중흥에스-클래스   55000        아파트         서울 도봉구
3     2024  11545  중앙하이빌1동2동   23000      연립다세대
4     2024  11590      종로빌리지   40000      연립다세대         서울 강남구

## 공공데이터 포털
- 국토교통부

In [ ]:
#PUBLIC_SERVICE_KEY = 'zleo38PS9vuuXhAXyut5so2vRlqHS8Ji2nRfwLR2TzmjdqVk4kKpjQWat%2BOqzG7aPU4B0r6FUuDf3RhAivWdYA%3D%3D'

import requests
import json
import pandas as pd
import xmltodict
PUBLIC_SERVICE_KEY = 'SDEjyCFJI1ki5hZaMAvBGUsre6U38rZKkVug%2BDGju9aAUp9G7%2B1tQagaeWcG2trJmx1%2BXe0JANCSgpGnLFuOPA%3D%3D'
# serviceKey = '인증키 입력'
pageNo = 1 # 페이지 번호
numOfRows = 500 # 한 페이지 결과수
LAWD_CD = 11500 # 지역코드
DEAL_YMD = 202101 # 계약월
url = f'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev?serviceKey={PUBLIC_SERVICE_KEY}&pageNo={pageNo}&numOfRows={numOfRows}&LAWD_CD={LAWD_CD}&DEAL_YMD={DEAL_YMD}'
req = requests.get(url)
# req.text
contents = xmltodict.parse(req.text)
data = pd.DataFrame(contents['response']['body']['items']['item'])
data.head()

,거래금액,거래유형,건축년도,년,도로명,도로명건물본번호코드,도로명건물부번호코드,도로명시군구코드,도로명일련번호코드,도로명지상지하코드,...,월,일,일련번호,전용면적,중개사소재지,지번,지역코드,층,해제사유발생일,해제여부
0,"70,000",None,1996,2021,양천로75길,00060,00000,11500,01,0,...,1,3,11500-30,59.92,None,291,11500,12,None,None
1,"85,500",None,1992,2021,양천로67길,00054,00000,11500,01,0,...,1,5,11500-23,84.7,None,287-1,11500,12,None,None
2,"98,000",None,2005,2021,공항대로,00637,00000,11500,01,0,...,1,5,11500-5104,84.84,None,282-19,11500,4,None,None
3,"80,300",None,1994,2021,양천로75길,00057,00000,11500,01,0,...,1,5,11500-28,84.34,None,288,11500,2,None,None
4,"74,800",None,1995,2021,양천로,00637,00000,11500,01,0,...,1,6,11500-16,59.94,None,244-2,11500,7,None,None

## 다중 데이터 수집

In [ ]:
SERVICE_KEY = '5379664f57696e6435314372485a54'
URL = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/1/1000/'

for i in range(1,4):
    URL = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/{1+(i-1)*1000}/{i*1000}/'
    print(URL)

http://openapi.seoul.go.kr:8088/5379664f57696e6435314372485a54/json/tbLnOpendataRtmsV/1/1000/
http://openapi.seoul.go.kr:8088/5379664f57696e6435314372485a54/json/tbLnOpendataRtmsV/1001/2000/
http://openapi.seoul.go.kr:8088/5379664f57696e6435314372485a54/json/tbLnOpendataRtmsV/2001/3000/

In [ ]:
import requests
import pandas as pd

SERVICE_KEY = '5379664f57696e6435314372485a54'

data = None
for j in range(1,5):
    url = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/{1+((j-1)*1000)}/{j*1000}'
    # url = f'http://openapi.seoul.go.kr:8088/{service_key}/json/tbLnOpendataRentV/1/1000/2023/11560'
    print(url)
    req = requests.get(url)
    content = req.json()
    con = content['tbLnOpendataRtmsV']['row']
    result = pd.DataFrame(con)
    data = pd.concat([data, result])
data = data.reset_index(drop=True)
data.head()

http://openapi.seoul.go.kr:8088/5379664f57696e6435314372485a54/json/tbLnOpendataRtmsV/1/1000
http://openapi.seoul.go.kr:8088/5379664f57696e6435314372485a54/json/tbLnOpendataRtmsV/1001/2000
http://openapi.seoul.go.kr:8088/5379664f57696e6435314372485a54/json/tbLnOpendataRtmsV/2001/3000
http://openapi.seoul.go.kr:8088/5379664f57696e6435314372485a54/json/tbLnOpendataRtmsV/3001/4000

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2024,11560,영등포구,10200,영등포동1가,1,대지,0121,0005,여의도리슈빌DS,...,20600,21.41,31.43,7.0,,,2020,오피스텔,중개거래,서울 영등포구
1,2024,11740,강동구,10900,천호동,1,대지,0090,0002,도우빌라,...,36700,48.69,46.66,-1.0,,,1991,연립다세대,중개거래,서울 강동구
2,2024,11320,도봉구,10800,도봉동,1,대지,0051,0012,중흥에스-클래스,...,55000,85.00,0.00,3.0,,,2004,아파트,중개거래,서울 도봉구
3,2024,11545,금천구,10200,독산동,1,대지,1006,0115,중앙하이빌1동2동,...,23000,28.68,14.88,4.0,,,2016,연립다세대,직거래,
4,2024,11590,동작구,10300,상도1동,1,대지,0419,0003,종로빌리지,...,40000,69.13,48.37,3.0,,,1991,연립다세대,중개거래,서울 강남구

In [ ]:
data

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2024,11560,영등포구,10200,영등포동1가,1,대지,0121,0005,여의도리슈빌DS,...,20600,21.41,31.43,7.0,,,2020,오피스텔,중개거래,서울 영등포구
1,2024,11740,강동구,10900,천호동,1,대지,0090,0002,도우빌라,...,36700,48.69,46.66,-1.0,,,1991,연립다세대,중개거래,서울 강동구
2,2024,11320,도봉구,10800,도봉동,1,대지,0051,0012,중흥에스-클래스,...,55000,85.00,0.00,3.0,,,2004,아파트,중개거래,서울 도봉구
3,2024,11545,금천구,10200,독산동,1,대지,1006,0115,중앙하이빌1동2동,...,23000,28.68,14.88,4.0,,,2016,연립다세대,직거래,
4,2024,11590,동작구,10300,상도1동,1,대지,0419,0003,종로빌리지,...,40000,69.13,48.37,3.0,,,1991,연립다세대,중개거래,서울 강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,2023,11290,성북구,13900,석관동,1,대지,0073,0014,(73-14),...,29000,28.49,20.41,5.0,,,2023,연립다세대,중개거래,서울 성북구
3996,2023,11440,마포구,10500,용강동,1,대지,0502,0000,래미안마포리버웰,...,170000,84.97,0.00,3.0,,,2015,아파트,중개거래,"서울 마포구, 서울 성동구"
3997,2023,11680,강남구,10600,대치동,1,대지,1014,0003,대치삼성,...,271000,97.35,0.00,17.0,,,2000,아파트,중개거래,"서울 강남구, 서울 금천구"
3998,2024,11200,성동구,11300,옥수동,1,대지,0561,0000,래미안 옥수 리버젠,...,220000,113.52,0.00,13.0,,,2012,아파트,중개거래,서울 성동구
3999,2023,11305,강북구,10100,미아동,1,대지,0258,0222,가람빌라,...,15000,52.60,35.90,-1.0,,,1986,연립다세대,중개거래,서울 강북구